spring:
  profiles:
    active: local
    #TODO удалить
  application:
    name: mdm-service

  kafka:
    bootstrap-servers: localhost:9391,localhost:9392,localhost:9393
    consumer:
      group-id: mdm-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


mdm-service:
  kafka:
    dlt-topic-suffix: .DLT
    user-event:
      topic-name: MDM.Change.Phone.IN.V1


external-api:
  service1:
    url: "http://localhost:8080/user-data-service-one"
    endpoints:
  service2:
    url: "http://localhost:8080/user-data-service-two"
    endpoints: