resilience4j:
  circuitbreaker:
    instances:
      defaultFaultToleranceConfig:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
  timelimiter:
    instances:
      defaultFaultToleranceConfig:
        timeoutDuration: 2s
  retry:
    instances:
      defaultFaultToleranceConfig:
        maxAttempts: 5
        waitDuration: 200ms
        retryExceptions:
          - feign.FeignException.ServiceUnavailable
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 1.25